article: https://www.bigclown.com/doc/projects/radio-motion-detector/
images:
  - title:
    url: https://cdn.myshoptet.com/usr/shop.hardwario.com/user/shop/category_portrait/171-2_motion-detector-kit-a1.jpg?5de56e1c
assembly:
  - name: BigClown PIR Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module

