article: https://developers.hardwario.com/projects/radio-motion-detector
images:
  - title:
    url: https://raw.githubusercontent.com/hardwario/website/master/static/kits-images/motion-detector/main.png
assembly:
  - name: HARDWARIO PIR Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module

